[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.26.0",
    "pandas>=2.1.3",
    "plotly==5.18.0",
    "python-dateutil==2.8.2",
    "requests==2.31.0",
    "streamlit==1.29.0",
]
